services:
  web:
    build: .
    restart: unless-stopped
    volumes:
      - ./sketches:/app/sketches
    environment:
      VIRTUAL_HOST: pixel.mahoney.best
      LETSENCRYPT_HOST: pixel.mahoney.best

networks:
  default:
    name: nginx
    external: true
